---
name: Deploy Preview

on: pull_request

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync . s3://pipeline-from-github-to-amplify

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "::set-output name=environment::$ENVIRONMENT"

      - name: Deploy to Amplify Console with CloudFormation
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          with:
            name: ${{ steps.env-name.outputs.environment }}
            template: stack.yaml
            no-fail-on-empty-changeset: "1"
            parameter-overrides: >-
              Name=${{ steps.env-name.outputs.environment }},
              Repository=https://github.com/${{ github.repository }},
              OauthToken=${{ secrets.AMPLIFY_TOKEN }},

      - name: Print default domain
        env:
          DefaultDomain: ${{ steps.amplify-stack.outputs.DefaultDomain }}
        run: |
          echo "Default Domain: $DefaultDomain"
---